SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP WHERE DEPTNO = 10
 UNION
 SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP WHERE DEPTNO = 10;
 
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP WHERE DEPTNO = 10
 UNION ALL
 SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP WHERE DEPTNO = 10;
 
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP
 MINUS
 SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP WHERE DEPTNO = 10;
 
SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP
 INTERSECT
 SELECT EMPNO, ENAME, SAL, DEPTNO, JOB
 FROM EMP WHERE DEPTNO = 10;
 
SELECT * FROM v$sqlfn_metadata;  -- 오라클 함수 리스트

SELECT func_id, argunum, datatype FROM v$sqlfn_arg_metadata; --오류

SELECT * FROM v$sqlfn_metadata
 WHERE datatype = 'STRING'; -- 오라클 문자열함수 리스트
 
SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME) --UPPER(ENAME):대문자, LOWER(ENAME):소문자, INITCAP(ENAME):Capitalize
 FROM EMP;

SELECT * FROM EMP
 WHERE UPPER(ENAME) = UPPER('scott');
 
SELECT ENAME, JOB, MGR, DEPTNO FROM EMP
 WHERE UPPER(ENAME) LIKE UPPER('%c%'); -- 이름에 C가 포함된 직원
 
SELECT ENAME, LENGTH(ENAME) FROM EMP; -- LENGTH 문자열 길이

SELECT ENAME, LENGTH(ENAME) FROM EMP
 WHERE LENGTH(ENAME) >= 5;
 
SELECT JOB
	,SUBSTR(JOB,1,2), SUBSTR(JOB,3,2), SUBSTR(JOB,5)
 FROM EMP; -- JOB에서 X1번째부터 X2개의 문자열 추출

SELECT JOB, SUBSTR(JOB, -LENGTH(JOB)), SUBSTR(JOB, -LENGTH(JOB),2), SUBSTR(JOB,3)   -- ???
 FROM EMP;

SELECT * FROM EMP
 WHERE INSTR(ENAME,'S')>0; -- S가 포함된 이름의 직원

SELECT INSTR('HELLO, ORACLE!','L')AS INSTR_1  -- INSTR(대상문자, 찾는글자, X1번째 글자부터 시작, 시작위치부터 X번째 글자)
	,INSTR('HELLO, ORACLE!','L',5)AS INSTR_2
	,INSTR('HELLO, ORACLE!','L',2,2)AS INSTR_3
 FROM DUAL;

SELECT '010-1234-5678' AS REPLACE_BEFORE
	,REPLACE('010-1234-5678', '-','')AS REPLACE_1 --문자열대체 REPLACE(대상문자, 찾는글자, 바꿀글자)
	,REPLACE('010-1234-5678', '-')AS REPLACE_2
 FROM DUAL;

SELECT 'Oracle', LPAD('Oracle', 10,'#')AS LPAD_1   --LPAD(대상문자, 총글자 개수, 왼편에 채울 글자)
	,RPAD('Oracle', 10,'*')AS RPAD_1
	,LPAD('Oracle', 10)AS LPAD_2
	,RPAD('Oracle', 10)AS RPAD_2
 FROM DUAL;

SELECT RPAD('971225-', 14, '*')AS RPAD_JMNO
	,RPAD('010-1234-', 13, '*')AS RPAD_PHONE
 FROM DUAL;

SELECT EMPNO, ENAME, CONCAT(EMPNO, ENAME)  -- CONCAT(문자,무운자,...) 문자무운자...  글자연결 
		,CONCAT(EMPNO, CONCAT(':',ENAME))
 FROM EMP
 WHERE ENAME = 'SMITH';

SELECT '['||TRIM(' _ _Oracle_ _ ')||']'AS TRIM
	,'['||TRIM(LEADING FROM ' _ _Oracle_ _ ')||']' AS TRIM_LEADING      --양쪽 공백제거. |: 파이프. 
	,'['||TRIM(TRAILING FROM ' __Oracle_ _ ')||']' AS TRIM_TRAILING     --코드 교체할때 FROM 넣었다뺏다 안하려고 BOTH FROM 없어도 되는데 넣어줌
	,'['||TRIM(BOTH FROM ' _ _Oracle_ _ ')||']' AS TRIM_BOTH
 FROM DUAL;



SELECT ROUND(1234.5678) AS R        -- ROUND(숫자, 반올림할 위치)
	,ROUND(1234.5678, 0) AS R_0
	,ROUND(1234.5678, 1) AS R_1
	,ROUND(1234.5678, 2) AS R_2
	,ROUND(1234.5678, -1) AS R_MINUS1
	,ROUND(1234.5678, -2) AS R_MINUS2
 FROM DUAL;
 
SELECT TRUNC(1234.5678) AS T        -- TRUNC(숫자, 버림할 위치)
	,TRUNC(1234.5678, 0) AS T_0
	,TRUNC(1234.5678, 1) AS T_1
	,TRUNC(1234.5678, 2) AS T_2
	,TRUNC(1234.5678, -1) AS T_MINUS1
	,TRUNC(1234.5678, -2) AS T_MINUS2
 FROM DUAL;
 
SELECT CEIL (3.14) AS CEIL, FLOOR(3.14) AS FLOOR       -- CEIL (정수로 반올림할 숫자) 
	,CEIL (-3.14) AS CEIL_M, FLOOR(-3.14) AS FLOOR_M   -- ???
 FROM DUAL;

SELECT MOD (15,6), MOD(10,2), MOD(11,2) FROM DUAL;   -- 나머지 구하기 : MOD(기준값, 나누는 숫자)

SELECT POWER (3,2), POWER(-3,3)  -- POWER(숫자, 의 몇 제곱승)
 FROM DUAL;

SELECT ABS(-100), ABS(100), ABS(0)    -- ABS(숫자) :절대값
 FROM DUAL;

SELECT SIGN(-100), SIGN(100), SIGN(0)     -- 부호반환..??
 FROM DUAL;

SELECT REMAINDER(15,4) AS c1    -- REMAINDER(기준값, 나눌 숫자) : 나머지 
	,REMAINDER(15,-4) AS c2
	,REMAINDER(-11,4) AS c3
	,REMAINDER(-11,-4) AS c4
	--,REMAINDER(15,0) AS c5    --0으로 나누면 오류발생. SQL Error [1476] [22012]: ORA-01476: divisor is equal to zero
 FROM DUAL;
 
SELECT SYSDATE AS NOW
		,SYSDATE -1 AS YESTERDAY
		,SYSDATE +1 AS TOMORROW
 FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE,3)    
 FROM DUAL;
 -- +3개월

SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 12*20) AS WORK20YEAR 
 FROM EMP;  -- 입사일, 20년차 근속일

SELECT EMPNO, ENAME, HIREDATE, SYSDATE
 FROM EMP
 WHERE ADD_MONTHS(HIREDATE, 12*40) > SYSDATE;
  -- 근속 40년 이상 직원

SELECT ENAME, HIREDATE, SYSDATE
		,MONTHS_BETWEEN(HIREDATE, SYSDATE)/12 AS YEAR1   --MONTHS_BETWEEN(시작, 끝) :  사이의 개월 수 
		,MONTHS_BETWEEN(SYSDATE, HIREDATE)/12 AS YEAR2
		,TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12) AS YEAR3
 FROM EMP;

SELECT SYSDATE
	,NEXT_DAY(SYSDATE,'월요일')
	,LAST_DAY(SYSDATE)
 FROM DUAL;

SELECT ENAME
	,EXTRACT(YEAR FROM HIREDATE) AS y
	,EXTRACT(MONTH FROM HIREDATE) AS m
	,EXTRACT(DAY FROM HIREDATE) AS d
 FROM EMP;

SELECT SYSDATE, ROUND(SYSDATE, 'CC') AS FORMAT_CC
		,ROUND(SYSDATE, 'YYYY') AS FORMAT_YYYY   -- 반올림
		,ROUND(SYSDATE, 'Q') AS FORMAT_Q
		,ROUND(SYSDATE, 'DDD') AS FORMAT_DDD
		,ROUND(SYSDATE, 'HH') AS FORMAT_HH
 FROM DUAL;

SELECT EMPNO, ENAME, EMPNO+'500' FROM EMP
 WHERE ENAME = 'SCOTT';


-- 잘못된 방법 --
SELECT 1300 - '1500', '1300'+1500 FROM DUAL;

SELECT '1,300' - '1,500' FROM DUAL;   -- 오류.  SQL Error [1722] [42000]: ORA-01722: invalid number
--------------

SELECT TO_NUMBER('1,500','9,999') - 1300  --명시적 형변환 방법
 FROM DUAL;

SELECT 'ABCD' + EMPNO, EMPNO
 FROM EMP
 WHERE ENAME = 'SCOTT';  -- 오류. 잘못된 명시적형변환. SQL Error [1722] [42000]: ORA-01722: invalid number














