/*
2페이지
(1) 테이블
(2) 외래키
(3) NULL

3페이지
(1) 문자셋(CharacterSet)
(2) 문자셋(CharSet)

4페이지
(1) VARCHAR2
(2) CHAR

5페이지
(1) 제약조건
(2) 기본키
(3) 외래키

6페이지
(1) 무결성(Integrity)
(2) 무결성
(3) 무결성

7페이지
(1) Unique
(2) Not null
(3) Index

 */

--8페이지
--(8-1)
SELECT DEPTNO
	,ROUND(AVG(SAL), 0) AS AVG_SAL
	,MAX(SAL) AS MAX_SAL
	,MIN(SAL) AS MIN_SAL
	,COUNT(SAL) AS CNT
 FROM EMP E
 GROUP BY DEPTNO;

--(8-2)
SELECT JOB
	,COUNT(*)
 FROM EMP
  GROUP BY JOB
 HAVING COUNT(JOB) >= 3;

--(8-3)
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR
	, DEPTNO
	, COUNT(*) AS CNT
FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO;

--9페이지
--(9-4)
SELECT CASE WHEN COMM IS NULL THEN 'N' ELSE 'Y' END AS EXIST_COMM
	, COUNT(*) AS CNT
FROM EMP
GROUP BY CASE WHEN COMM IS NULL THEN 'N' ELSE 'Y' END;

--(9-5)
SELECT DEPTNO
	, TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR
	, COUNT(*) AS CNT
	, MAX(SAL) AS MAX_SAL
	, SUM(SAL) AS SUM_SAL
	, AVG(SAL) AS AVG_SAL
 FROM EMP
 GROUP BY ROLLUP (DEPTNO, TO_CHAR(HIREDATE, 'YYYY'));

--10페이지
--(10-1)
SELECT B.DEPTNO 
      ,B.DNAME 
      ,A.EMPNO 
      ,A.ENAME 
      ,A.SAL 
FROM EMP A
    ,DEPT B
WHERE A.DEPTNO = B.DEPTNO 
AND A.SAL > 2000
ORDER BY B.DEPTNO 
; 

SELECT B.DEPTNO 
      ,B.DNAME 
      ,A.EMPNO 
      ,A.ENAME 
      ,A.SAL 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
WHERE A.SAL > 2000
ORDER BY B.DEPTNO 
; 

SELECT DEPTNO 
      ,DEPT.DNAME
      ,ROUND(AVG(SAL)) AS AVG_SAL
      ,MAX(SAL) AS MAX_SAL
      ,MIN(SAL) AS SUM_SAL
      ,COUNT(EMPNO) AS CNT
FROM EMP
NATURAL JOIN DEPT
GROUP BY DEPTNO
        ,DEPT.DNAME 
;

--11페이지
SELECT D.DEPTNO 
      ,D.DNAME 
      ,E.EMPNO 
      ,E.ENAME 
      ,E.JOB 
      ,E.SAL 
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO  = D.DEPTNO
ORDER BY D.DEPTNO 
;

SELECT D.DEPTNO 
      ,D.DNAME 
      ,E.EMPNO 
      ,E.ENAME 
      ,E.JOB 
      ,E.SAL
      ,S.LOSAL 
      ,S.HISAL 
      ,S.GRADE 
      ,M.EMPNO AS MGR_EMPNO
      ,M.ENAME AS MGR_ENAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
LEFT OUTER  JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
LEFT OUTER  JOIN EMP M
ON E.MGR  = M.EMPNO 
ORDER BY D.DEPTNO, E.EMPNO 
;


--12페이지
SELECT A.JOB
      ,A.EMPNO 
      ,A.ENAME 
      ,A.SAL 
      ,B.DEPTNO 
      ,B.DNAME 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
WHERE A.JOB = (SELECT JOB
   			   FROM EMP
   			   WHERE ENAME='ALLEN')
;

SELECT A.EMPNO 
      ,A.ENAME 
      ,B.DNAME 
      ,A.HIREDATE 
      ,B.LOC 
      ,A.SAL 
      ,S.GRADE 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
LEFT OUTER  JOIN SALGRADE S
ON A.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE SAL > (SELECT AVG(SAL) 
   			 FROM EMP)
ORDER BY A.SAL DESC, HIREDATE DESC
;


--13페이지
SELECT A.EMPNO 
	  ,A.ENAME 
	  ,A.JOB 
	  ,A.DEPTNO 
	  ,B.DNAME 
	  ,B.LOC 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
WHERE A.DEPTNO = 10
AND JOB NOT IN (SELECT JOB
  				FROM EMP
  				WHERE DEPTNO = 30)
;


SELECT A.EMPNO 
	  ,A.ENAME 
	  ,A.SAL 
	  ,S.GRADE 
FROM EMP A
LEFT OUTER  JOIN SALGRADE S
ON A.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE A.SAL > (SELECT MAX(SAL)
 			   FROM EMP
 			   WHERE JOB = 'SALESMAN')
;


SELECT A.EMPNO 
	  ,A.ENAME 
	  ,A.SAL 
	  ,S.GRADE 
FROM EMP A
LEFT OUTER  JOIN SALGRADE S
ON A.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE A.SAL > ALL (SELECT SAL
 			       FROM EMP
 			       WHERE JOB = 'SALESMAN')
;
