--실습과제
/*
 * 1. 원자성, 완전 함수적 종속, 이행적 종속 제거
 * 2. 제3정규화, 제2정규화
 * 3. inner join, left join, right join, outer join
 * 4. 반정규화
 * 5. 인댁스, 인덱스, 인덱스, 인덱스
 * 6. 트랜잭션, 원자성, 일관성
 */

--8페이지 1
CREATE TABLE DEPT_TEST
	AS (SELECT * FROM dept);

SELECT *
 FROM DEPT_TEST;

INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC)
 VALUES(50, 'ORACLE', 'BUSAN');

INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC)
 VALUES(60, 'SQL', 'ILSAN');
ㄴ
INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC)
 VALUES(70, 'SELECT', 'INCHEON');

INSERT INTO DEPT_TEST(DEPTNO, DNAME, LOC)
 VALUES(80, 'DML', 'BUNDANG');

SELECT *
 FROM DEPT_TEST;
 
--8페이지 2
SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL
 FROM EMP;
 

CREATE TABLE EMP_TEST
	AS (SELECT EMPNO, ENAME, JOB, MGR, HIREDATE, SAL
		 FROM EMP
		 WHERE 1<>1
		);
	
SELECT *
 FROM EMP_TEST;

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7201, 'TEST_USER1', 'MANAGER', 7788, '2016/01/02', 4500);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7202, 'TEST_USER2', 'CLERK', 7201, '2016/02/21', 1800);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, '2016/04/11', 3400);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, '2016/05/31', 2700);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7205, 'TEST_USER5', 'CLERK', 7201, '2016/07/20', 2600);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7206, 'TEST_USER6', 'CLERK', 7201, '2016/09/08', 2600);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, '2016/10/28', 2300);

INSERT INTO EMP_TEST(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL)
 VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, '2018/03/09', 1200);

SELECT *
 FROM EMP_TEST
 ORDER BY ENAME;





--3
UPDATE EMP_TEST
SET DEPTNO = 70
WHERE SAL > (SELECT AVG(SAL)
             FROM EMP_TEST
             WHERE DEPTNO = 50)
;             

--4
UPDATE EMP_TEST
SET DEPTNO = 80,
    SAL = SAL*1.2
WHERE HIREDATE > (SELECT MIN(HIREDATE)
                  FROM EMP_TEST
                  WHERE DEPTNO = 60)
;             


--(2)--
--1
CREATE TABLE EMP_NEW(
 EMPNO 		NUMBER(5),
 ENAME 		VARCHAR2(20),
 JOB		VARCHAR2(10),
 MGR 		NUMBER(5),
 HIREDATE	DATE,
 SAL  		NUMBER(7,2),
 DEPTNO 	NUMBER(2)
);

--2
ALTER TABLE EMP_NEW
ADD RESIGN_DATE DATE
;

--3
ALTER TABLE EMP_NEW
ADD SUR_NAME VARCHAR2(5)
;

--4
ALTER TABLE EMP_NEW
MODIFY SUR_NAME VARCHAR2(10)
;

--5
ALTER TABLE EMP_NEW
RENAME COLUMN ENAME TO FULL_NAME
;

--(3)--
--1
CREATE TABLE EMP_IDX AS
SELECT *
FROM EMP
;

CREATE INDEX EMP_EMPNO_IDX ON EMP_IDX(EMPNO);

--2
SELECT *
FROM USER_INDEXES
WHERE INDEX_NAME LIKE 'EMP_EMPNO_IDX'
;


--3
CREATE VIEW EMP_VIEW AS
SELECT EMPNO
      ,ENAME
      ,JOB
      ,DEPTNO
      ,SAL
      ,NVL2(COMM,'Y','N') AS COMM
FROM EMP_IDX
WHERE SAL >= 2000
;


--(4)--
--1. CONSTRAINTS
--2. UNIQUE
--3. NOT NULL
--4. PRIMARY KEY
--5. FOREIGN KEY
